.TH "TORCS" "6" "1.2.2" "Rudy Godoy" "Games"
.SH NOMBRE
torcs \- Juego simulador de carrera de autos en 3D usando OpenGL
.SH DESCRIPCIÓN
TORCS, El simulador de carrera de autos, es una simulación de carrera de
autos que le permite conducir en carreras contra oponentes simulados por
ordenador. También puede construir sus propios conductores
contolados por ordenador (también llamados robots) en C o C++.
.br
TORCS es un programa de software libre licenciado bajo la GNU General
Public License Version 2 o posterior.
.SH OPCIONES
Este programa no tiene ninguna opción.
.SH VÉASE TAMBIÉN
Para un manual mas detallado sobre como jugar, por favor véa: 
.br
http://\:torcs.\:sourceforge.\:net/?name=Sections?op=viewarticle&artid=10
.SH AUTOR
Esta página de manual ha sido escrita por Rudy Godoy <rudy@stone-head.org>,
para el proyecto Debian (pero puede ser usada por otros).
